@ECHO OFF
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/11/15/web-archive/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/11/15/who-i-am/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/author/crypt3r/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/11/15/who-i-am/#respond
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/11/15/web-archive/#respond
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/category/internet/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/11/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/11/15/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/check
start https://fawdaw.com/save/save.php?url=https://check.crypt3r.com/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/11/16/my-job/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/category/networking/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/upcoming-projects/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/my-stuff/
start https://fawdaw.com/save/save.php?url=https://crypt3r.com/2017/11/18/foldinghome/
pause